version: "3.8"

services:
  backend:
    container_name: backend
    image: vriera/backend:latest
    restart: always
    hostname: "backend"
    environment: 
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=secret_password
      - DB_DATABASE=database
    depends_on:
      - database
    networks:
      - api
      - database
      

  database:
    container_name: database
    image: postgres
    restart: always
    networks: 
      - database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_DB=database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  nginx:
    image: vriera/nginx-spa:latest
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
    networks:
      - api
      - default
volumes:
  postgres_data:
  
networks:
  database:
    external: false
  api:
    external: false
  