version: "3.8"

services:
  database:
    container_name: database
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    networks: 
      - database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_DB=database
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
  