
export const MANAGER_REPOSITORY = "MANAGER_REPOSITORY"
export const DATA_SOURCE = "DATA_SOURCE"
export const MENU_ITEM_REPOSITORY = "MENU_ITEM_REPOSITORY"
export const WAITER_REPOSITORY = "WAITER_REPOSITORY"

export const PAGE_DEFAULT_SIZE = 10;
